### ISSUE TITLE
Internal Server Error.

### ISSUE THREAD

**Issue by pajaskowiak** [molnarmark/carbonSublime#17] opened 2018-08-03 15:45 UTC
Hi!
I'm trying to use the Sublime Text Plugin, but when it opens the browser window I only get 500 | Internal Server Error. Any ideas on how to solve this? If you need any additional information I'll happily provide :)

**Comment by gh640** [comment] 2018-08-04 05:57
Hi!

Thank you for sharing the issue :)

Can you please share the actual steps to reproduce the error (with which I can reproduce the same error)? Does it happen whenever you call the command? Or, does it happen with specific patterns of text? In the latter case, can you provide the actual text you met the error with? (I guess it happens only with some patterns of text.)

**Comment by pajaskowiak** [comment] 2018-08-06 16:21
Hi there,

As it seems the problem appears only with C code (I tried python, everything was fine). Simple code like:

#include <stdio.h>

int main() {
   int a[3] = {6, 2, 3};
   printf("%d",*(a+1));
   return 0;
} 

will cause the error. Ii I send a single line of code it works. Sending the whole code, however, produces an error.

Tks in advance.

**Comment by gh640** [comment] 2018-08-07 04:50
Thank you for sharing the detail!

I could reproduce the error with your code. I narrowed down the cause and found that including `%` leads to the error in the carbon server. We can produce the error just by selecting one `%` and running the carbon command.

This package properly sanitises the code before sending it to the carbon server and the problem is on the carbon app which doesn't work for `%` if I understand it correctly. What do you think?

**Comment by gh640** [comment] 2018-08-07 06:37
I reported the issue at https://github.com/dawnlabs/carbon/issues/452 . If I misunderstand it, please let me know.

**Comment by gh640** [comment] 2018-08-08 01:09
@pajaskowiak The issue https://github.com/dawnlabs/carbon/issues/452 has been resolved and we don't get the error any more, I believe :)

I close this but please feel free to reopen this if you need to. Thanks!

**Closed as completed by gh640** 2018-08-08 01:09 UTC
